"""Skill registry definitions."""

from __future__ import annotations

from typing import Dict

from anime_pipeline_graph.domain.enums import BackendType, CostLevel, LatencyLevel
from anime_pipeline_graph.domain.models import SkillSpec


class SkillRegistry:
    """Container for all schedulable skills."""

    def __init__(self) -> None:
        self.skills: Dict[str, SkillSpec] = {
            "base_generation": SkillSpec(
                name="base_generation",
                description="基础动漫图生成",
                backend=BackendType.HF_LOCAL,
                model="black-forest-labs/FLUX.1-dev",
                input_types=["prompt_pack", "char_anchor", "scene_pack", "pose_plan_json", "pose_skeleton"],
                output_types=["generated_images"],
                best_for=["first render"],
                preconditions=["prompt_pack_ready"],
                supports_multi_frame=True,
                supports_multi_character=True,
                cost_level=CostLevel.HIGH,
                latency_level=LatencyLevel.HIGH,
            ),
            "character_bind": SkillSpec(
                name="character_bind",
                description="角色锚定",
                backend=BackendType.HF_LOCAL,
                model="black-forest-labs/FLUX.1-Kontext-dev + optional LoRA",
                input_types=["character_references", "character_brief", "lora_path"],
                output_types=["char_anchor"],
                best_for=["identity"],
                preconditions=["character_exists"],
                supports_multi_frame=True,
                supports_multi_character=True,
                cost_level=CostLevel.MEDIUM,
                latency_level=LatencyLevel.MEDIUM,
            ),
            "edit": SkillSpec(
                name="edit",
                description="无 mask 编辑",
                backend=BackendType.HF_LOCAL,
                model="black-forest-labs/FLUX.1-Kontext-dev",
                input_types=["image", "instruction", "refs"],
                output_types=["edited_image"],
                best_for=["global correction"],
                preconditions=["image_exists"],
                supports_multi_frame=True,
                supports_multi_character=True,
                cost_level=CostLevel.MEDIUM,
                latency_level=LatencyLevel.MEDIUM,
            ),
            "fill_edit": SkillSpec(
                name="fill_edit",
                description="有 mask 局部编辑",
                backend=BackendType.HF_LOCAL,
                model="black-forest-labs/FLUX.1-Fill-dev",
                input_types=["image", "mask", "instruction"],
                output_types=["edited_image"],
                best_for=["local correction"],
                preconditions=["image_exists"],
                supports_multi_frame=True,
                supports_multi_character=True,
                cost_level=CostLevel.HIGH,
                latency_level=LatencyLevel.MEDIUM,
            ),
            "scene_condition": SkillSpec(
                name="scene_condition",
                description="构建场景条件包",
                backend=BackendType.BUILDER,
                model="scene reference + text summary",
                input_types=["scene_references", "prompt", "setting_docs"],
                output_types=["scene_pack"],
                best_for=["scene conditioning"],
                preconditions=[],
                supports_multi_frame=True,
                supports_multi_character=True,
                cost_level=CostLevel.LOW,
                latency_level=LatencyLevel.LOW,
            ),
            "pose_plan": SkillSpec(
                name="pose_plan",
                description="Qwen 结构化动作规划",
                backend=BackendType.QWEN_API,
                model="qwen api",
                input_types=["character_names", "prompt"],
                output_types=["pose_plan_json"],
                best_for=["pose planning"],
                preconditions=[],
                supports_multi_frame=True,
                supports_multi_character=True,
                cost_level=CostLevel.LOW,
                latency_level=LatencyLevel.LOW,
            ),
            "shot_plan": SkillSpec(
                name="shot_plan",
                description="Qwen 分镜镜头语言规划（景别/机位/构图）",
                backend=BackendType.QWEN_API,
                model="qwen api",
                input_types=["character_names", "frame_descriptions", "num_frames", "scene_names"],
                output_types=["shot_plan_json"],
                best_for=["cinematic shot planning"],
                preconditions=[],
                supports_multi_frame=True,
                supports_multi_character=True,
                cost_level=CostLevel.LOW,
                latency_level=LatencyLevel.LOW,
            ),
            "transition_plan": SkillSpec(
                name="transition_plan",
                description="Qwen 帧间过渡类型与连续性规划",
                backend=BackendType.QWEN_API,
                model="qwen api",
                input_types=["frame_descriptions", "num_frames", "task_type"],
                output_types=["transition_plan_json"],
                best_for=["transition continuity"],
                preconditions=[],
                supports_multi_frame=True,
                supports_multi_character=True,
                cost_level=CostLevel.LOW,
                latency_level=LatencyLevel.LOW,
            ),
            "expression_plan": SkillSpec(
                name="expression_plan",
                description="Qwen 逐帧表情规划",
                backend=BackendType.QWEN_API,
                model="qwen api",
                input_types=["character_names", "frame_descriptions", "num_frames"],
                output_types=["expression_plan_json"],
                best_for=["facial expression consistency"],
                preconditions=[],
                supports_multi_frame=True,
                supports_multi_character=True,
                cost_level=CostLevel.LOW,
                latency_level=LatencyLevel.LOW,
            ),
            "continuity_state_tracker": SkillSpec(
                name="continuity_state_tracker",
                description="跨帧连续性状态账本（角色/场景/道具/叙事）",
                backend=BackendType.QWEN_API,
                model="qwen api",
                input_types=[
                    "character_names",
                    "scene_names",
                    "frame_descriptions",
                    "num_frames",
                    "shot_plan_json",
                    "transition_plan_json",
                    "expression_plan_json",
                ],
                output_types=["continuity_state"],
                best_for=["story continuity ledger"],
                preconditions=[],
                supports_multi_frame=True,
                supports_multi_character=True,
                cost_level=CostLevel.LOW,
                latency_level=LatencyLevel.LOW,
            ),
            "visual_style_plan": SkillSpec(
                name="visual_style_plan",
                description="序列风格圣经（画风/色板/光照/线条密度）",
                backend=BackendType.QWEN_API,
                model="qwen api",
                input_types=["user_text", "task_type", "scene_names", "character_names", "num_frames"],
                output_types=["visual_style_plan"],
                best_for=["style consistency"],
                preconditions=[],
                supports_multi_frame=True,
                supports_multi_character=True,
                cost_level=CostLevel.LOW,
                latency_level=LatencyLevel.LOW,
            ),
            "pose_extract": SkillSpec(
                name="pose_extract",
                description="提取 skeleton 辅助条件",
                backend=BackendType.LOCAL_PREPROCESS,
                model="controlnet_aux / openpose",
                input_types=["action_reference"],
                output_types=["pose_skeleton"],
                best_for=["pose reference"],
                preconditions=[],
                supports_multi_frame=True,
                supports_multi_character=True,
                cost_level=CostLevel.LOW,
                latency_level=LatencyLevel.LOW,
            ),
            "story_decompose": SkillSpec(
                name="story_decompose",
                description="剧情拆分 frame specs",
                backend=BackendType.QWEN_API,
                model="qwen api",
                input_types=["prompt", "num_frames"],
                output_types=["frame_specs"],
                best_for=["storyboard"],
                preconditions=["num_frames>1"],
                supports_multi_frame=True,
                supports_multi_character=True,
                cost_level=CostLevel.LOW,
                latency_level=LatencyLevel.LOW,
            ),
            "judge": SkillSpec(
                name="judge",
                description="结果评估",
                backend=BackendType.QWEN_API,
                model="qwen api",
                input_types=["images", "task_spec"],
                output_types=["judge_report"],
                best_for=["evaluation"],
                preconditions=["images_ready"],
                supports_multi_frame=True,
                supports_multi_character=True,
                cost_level=CostLevel.LOW,
                latency_level=LatencyLevel.LOW,
            ),
            "refine": SkillSpec(
                name="refine",
                description="基于 judge 报告修复",
                backend=BackendType.HF_LOCAL,
                model="kontext/fill",
                input_types=["image", "judge_report"],
                output_types=["refined_image"],
                best_for=["repair"],
                preconditions=["judge_failed"],
                supports_multi_frame=True,
                supports_multi_character=True,
                cost_level=CostLevel.MEDIUM,
                latency_level=LatencyLevel.MEDIUM,
            ),
            "prompt_pack_builder": SkillSpec(
                name="prompt_pack_builder",
                description="聚合角色/场景/动作条件生成 prompt pack",
                backend=BackendType.BUILDER,
                model="builder",
                input_types=["task_spec", "scene_pack", "char_anchor", "pose_plan_json", "expression_plan_json"],
                output_types=["prompt_pack"],
                best_for=["prompt compose"],
                preconditions=[],
                supports_multi_frame=True,
                supports_multi_character=True,
                cost_level=CostLevel.LOW,
                latency_level=LatencyLevel.LOW,
            ),
            "asset_normalizer": SkillSpec(
                name="asset_normalizer",
                description="统一参考图格式",
                backend=BackendType.BUILDER,
                model="Pillow",
                input_types=["images"],
                output_types=["normalized_images"],
                best_for=["io normalization"],
                preconditions=[],
                supports_multi_frame=True,
                supports_multi_character=True,
                cost_level=CostLevel.LOW,
                latency_level=LatencyLevel.LOW,
            ),
        }

    def as_dict(self) -> Dict[str, dict]:
        """Return JSON-like registry payload."""
        return {k: v.model_dump(mode="json") for k, v in self.skills.items()}
